# Generated by Django 4.2.9 on 2024-01-30 19:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sensor", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="airpollution",
            name="value",
            field=models.BooleanField(),
        ),
    ]
